language: java
jdk:
- oraclejdk8
env:
  global:
  - ACTIVATOR_VERSION=1.3.7
  - ACTIVATOR_ZIP_FILE=typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - ACTIVATOR_ZIP_URL=http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/${ACTIVATOR_ZIP_FILE}
  - PLAY2_HOME=${TRAVIS_BUILD_DIR}/activator-${ACTIVATOR_VERSION}-minimal
  - SBT_EXECUTABLE_NAME=activator
  - GH_REF=github.com/theAgileFactory/app-framework
  - secure: z6R9MBtV6Qrxk3FXQhYDzdbXTUsFcSNMwgtbo1O5Ev5VjsUeDijDrjMo8Z6Sl2pE1cqOomi69OxkH/axv6Goi2jPw5vNOwguh63Yr6F3FoletbdUf7gW58sYN17K5e6Lon12YLgCGjM6YqrtQR+qNvn+O319Wa61Kg/lyX6f+wOX4dmy9X4woMcjH6IX1c6SRDt6ukff/sxmPJpzP/1o+KS2sKVrYVKV7roh4Mhpkm3dO8PXKNj6pKXX2N4rd8lkSB2UGuh4zH8Zhkt8hdGLE3lvw0d/YL5Me67EGQvrEBWTiXI6p1gFvIXsM9Dq0vX9AasUo0Yy0FeTGd8YRgRXmmwmxA0xv86C04nStyOoXdiGWInejrBbCFoteR2En0zHvov82cYs/SoMnqXAOO0NoUspW35A3CaKJ/5RcA3dg2I8t2jIa5nefHf5tJizkaQaJDUFkzbkz8jU/7nb2DcjQUdfnYlEjzZLPpohoIzV4TsqCjklLbc8HdD5GuHHV6zXX1oqLJ0d6lRfBuauPdqmk7tDAW+jiUuuiOD9gUmQklVUZuuYhchyVvSBOx2mCYlbheGU/j9+eQ5os/avuZcIr7sH5Hq327FMyw1PH2xtTEMk9gozb4ZTMt0ocV6b4eaJ5Qaqh4q3xTGkgvrGENWAcoMcBckoMQmzUUglvCi3wGU=
  - secure: yl+u8xHloqIMNwEvPX6rfxnzSs2xgo/Jf4Fkc0zQ0qagb8JdvbvMfhJsZr5DsFOxW2w4p2yYZfMDplnU/AAI1DSHuXJtyA+cX2pBr/qvNInmnLLzvn8rlIkRNj7KwQcP89wwLccAo5/JJjEToilxd8FNBSsipl659EvXlqHgyrRCY8RAf16AMMw3koUFXWG7FL1FFQSZX8rWhy3lHKCTq6f54dLc/gJvCjzl651GJJvLdhU2Jc+a3dQmbfw/XXkuIqGXCnMk00feIFXWNTEgltgXC6BO4rqBxv7pyJyO8T58sgwmykMh/Sx7egn0vGjyYOrklSNmt4Gl3RHOqmYylDZaDzyVta+u83ehXS1rk6yENeffuNhDXcVNd5/1ejFa4pLhZXl/YJX52HDdF4Tql4QAIRKCZGqfMNAyF9qZrPt1cBuifeZsz/LlsXJFhZXL8tgHgeYZxIyywZNUl+k9Vs9A02B2EwFjihwAUzoLG28oLO/B7D16U6Ich8ydGanT74FEtGO3fGN6IJV3umFxY33ItFMAhFB2UBY7NM+dYYiCpI8APISjqxSJVFJ6erS3TdcyM1EBSjC1p17v8wUjGDac3C56rg13zR3clDtGMfky1loHmpsh8n3GiFrD4nIDLA10uYy377CTqlQOag9jpmqAxg6Qvv2k+LA3ZQ4yZWw=
  - secure: hncAaHIuysbpIBvIsz57xoWN8KCpS0sLKWGWmOmL67sq5NBHWTWAZFivy7VZ+Dl93VSgvInlcOpQaN88LrrFR6/QypfGRz7elX4TlRQnN3EYUlTkOXPObU3yfz5gdVcxvhBEWVvzPlfslgN1CFuaOSToesgmsRSQrzONhlLx+3r7YgSuiDo+4fSAI9HcnFgvesuJp7bEfhayumwvxiW+Yn/bFX1hH60mf7MMdj6b5R93iML7Z6/Ss5TdtXW9r0LqxnpPOKrDr9CS17PW4bUXBhPof5zrUoiO7sGUaWDBHSdKnBv54xGcC59OZCnzgmvAEKTgphaa6sorKBYuxgU0oBpR4AdoToYxml1vSitiD7TWD0/RPrMVm/b+6ASNup/OV86MVRvKV80aOEBQ3TuZ0Ux+u8kIZ14I9CLIDUoETf7F5eQZ1+yd0Q7BN84zL6B/sBR8XycLbm3QTAW7s9Wt+bn2vGVGgxUk2U6Yel4KP26vo2xt8LlNA4RqBBV9ok6PO4v3Z73DmuOMkd+Mbo9NQxpdyTbO0KDSx1IXSqn7kXlqoB8yzBL+JmK8a4ptdDr/6gDyWb4TJ2Qs7hcjVpzTiW/DqL2Rpk9t9myEdCPKf/6ozEaac9Hio3qKAWLHizRFtj3pgEwzzDpShFgyrRC5IqNIyPuGmrzTSC7pUHhoJaM=
  - secure: dp4p+sgzEQI4Axe7jh8k+gr08rnieV0vgn+VT2ezvnHAU8rTNrPr3Qt860xbFQehtp3/EMPeDdOMJfHXdbh3lqoec54U/qb/KPuPyMuBhYR04GV5HNlb7Esg0ffpAXUhH2m5/npjCfCXIFfX9QNiG9CqZMVZAGmJrnOJ9SSdauxvXcLoEqho9sMlo+TPDuTvtQIdIIVHvacM8jB2HVs1mJqQ1hcBXvnBFu5NdmN/CME4+yTBAD0JQUa+0kLCRBj+7NPQdE4+uRZFZqLVIseCXlbHGyvbjRK9w9zkNoXnD3PRc0omA1qruaks+EoRfBeIlYQQsLMdcrVIBjBSoX40RNKmeS20i2QaXlX6T10FEJYXq7PFbypeHlVflUlEPDtZFUCy79pEFwNp/9FAJnaLpQOEFUTO0Di1ZFU3hFCw1Ko1I5LCY15JkDfX5O7p299EGJNeMk8WxLS/oJjr/cZjK4YnZrSfVMExJMkEqhk5V9PBTy+BR6hlWkyfnvHxLtBEyp+EJy9GdhFRsoPoZ+nN56Oy/0NwNXwADp/KVdT407enfaFzOxybgaC2jPAlSKOURhUXN4L/sOKTKzdmtFSHC+3wcqaeoTOvuspwVJHM0sDfXVH5m+auVTQET591K4zUcDIcc2rCXEO7wuULgyRDGLmC44zRP1N4GW2D1UF5GzY=
  - secure: wdHhXdkX4CoUJsmIh1LtttNLz+ytOBgxtB5LXJXAd4KQUnOk7YfdWa7iWuXZb8f4qDkpQCRdKGt8VrwCZv3d1Y82ecVuq7RZYEd+AUkWhqdRuNqzMcy1o4rQo4WFPIORFrA4+U4IiscG2tsm0z4zRYtcHDgKrthScpMYlvXH4H298FnXFVxFj7CXSqNmUKaOsuoYrGvElnwpnW8wLNjSH+gXYtjefMihZCZ2ZhErpDnC1OpnYtVmJE29SQ3V4WZpyfQwjMIsvbY0FYLoICwmFPImYiF6taHvxaEBIO8Kg0xwpY69VpzxZZouT8+Fctyiy3lO3/A5D5liLq/9Nf4bpnaSLAhkLz6wrjJDHcN/dYhifWdQEVMK9Fsqr6S19bSrJ/HvtCZ/UkvjWnyoq55gkTUGH0En2s+fSZz2TP/CKPd5EbENIKoZyiWN+Mvn6ruUuf+dazN02DGVEvpiF5S78tqbaHptFABZaElp8oprT6P7iymVJfP0t3DNsVR8J/bm92uI29JFaqLMSbtbTNRY1iGdBjXMTRnD6cZ6RTFvzYLYtbvnNQdpcvud1vdkamAjyXwVVJ7KTGyyizv5JV7KK2sYgETTgJTVX2ZpYJMmYrTKRuQtCfXc3zSj3ODqtHsCnePPsdMdqArvvwmgmr6s/I3i9RbfXOWtUE5dYsCj8gE=
before_install:
- sudo apt-get update
- sudo apt-get install --only-upgrade -y oracle-java8-installer
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out secring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out pubring.gpg -d
- echo "<settings><servers><server><id>ossrh</id><username>\${OSSRH_JIRA_USERNAME}</username><password>\${OSSRH_JIRA_PASSWORD}</password></server></servers></settings>" > $HOME/.m2/settings.xml

install:
- wget ${ACTIVATOR_ZIP_URL}
- unzip -q ${ACTIVATOR_ZIP_FILE}
script:
- mvn -f pom2.xml -Dgpg.defaultKeyring=false -Dgpg-keyname=F79C926B -Dgpg.passphrase=${GPG_PASSPHRASE} -Dgpg.publicKeyring=pubring.gpg -Dgpg.secretKeyring=secring.gpg clean install
after_script:
- rm secring.gpg
- rm pubring.gpg
- rm $HOME/.m2/settings.xml
notifications:
  email: true
branches:
  only:
  - master
scala:
- 2.11.8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.sbt
  - $HOME/.ivy
