language: java
jdk:
- oraclejdk8
env:
  global:
  - ACTIVATOR_VERSION=1.3.7
  - ACTIVATOR_ZIP_FILE=typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - ACTIVATOR_ZIP_URL=http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/${ACTIVATOR_ZIP_FILE}
  - PLAY2_HOME=${TRAVIS_BUILD_DIR}/activator-${ACTIVATOR_VERSION}-minimal
  - SBT_EXECUTABLE_NAME=activator
  - GH_REF=github.com/theAgileFactory/app-framework
  - secure: JDjsi22sqWMWk2plr+OQ0+ROPNTXWQRtH9JzlFZfuTO7pFwfzJUualAQRxcrypejXeGGKF8SsvUWvPTsK3W/xO0Mywwg/U1TEEiAMLMF2nAkrpzOmRAnjjtZ1Zdmtrb8RLluoZKPkqEp040ofjdEJlLsP54snrEBqNIWj08QyKgxqZosckKxrAdAs0mmtngoe6PhoBtjynnxJarq1NrwDLbVHUz6NfgomkWHKoN9J+cpn+Xu1k0m3Qtj6kBUi+GBDAShIGOz3M5NSgYw6yHSu7Uot5EIOkygf9cUYX62PqL/ZeLBS/Sku8DYwK6/xxGiN5orVfN+S5nFFLFS2YiOvd1+5POs9+FEsDLr1HO/y4jG88jrS5CcLf255iX4r46UFbQ76j0dx9G5QhwziRipPQbzYqfcvb6XhA4Jxq5PRvF8L+pZpChviwDlFpkZmpucl+3CY3snK8COfW5r5DFj00VlXmEtQV5ZjbBbjOMv4IvYyUY/MdM3IzlOCnafh98qGq/jS1AypvISL9umQxuWQyRJO56JY2c04wQtPtEZG72phGC0Vy9ky9aP2a1CjcKWUO2Epb8vIihxHkSuInAlP9TdPpVsnkFKOMx3j+A8xKKrjP0JfNpqbaf3897FxlJ6u1m4fwJe1N5u+G67Nnm0JCoP3Mhb+S0lL8/q0Py8p4I=
  - secure: eHqxqALQggpmjShYb6LrfwcSChGwQG+cw1FSmiYelOf2Efjggcxo1v2OEE9fJgCpaEFgfEz6T66lrsBAvIJX1Ny84CG4YZxvMmgrDwm9yNsBrC8ZEqbE1m5+btAC0t26OTdN6/wVtbpesy2NRoTnOAftVh0RQuSgfyO2ad/WTrZakpDimV9xALColR3fmwI/DzL5CqLTcbxzL6gtE+fWgFzjmMVXTIqc+FqltBOlrj4I7+A01Z/7GPIRY5j2B/9/Fq6ekXMKSV2JpgYmI+sHWpzy7tmThq9RmKzOqf1edxw+WpXsodlhrqrtDO6LJDiQ1EjL/SMd3V9JzhBNPz9RNYcWLo8mo/MTh2usedeaWUMRBRmJGiEsxxTNJ3US8bBPIV0jI7h8wUAgAs3QByDSxe0V/hhJdDL9RzulIb0KzBjDpDqYced2AhdzOIQjI5rWvo6uRB5or1rns4wRRDvyRVpJWqLT1jO6rRwhiGeBniCZ24i65SlxpKCb8v9SV+NHChSJwWUQ6oK1xGeok/tu2pv+lmW2tHDLJaL875NqsikOhRDNPexBR1pKDbIpjs3qD+++hHLLhZWLU7Q4TCvWVK35bYNWQLdwPBQcptF9X7Y5dNQHiYPT8jq/cNM9APDJlR4r1hH+6LVdUw3Ze0wlULqXA2g4tCSywwSfBTUNyAU=
  - secure: VaPMmEjzSdELkThTkcqI5dCodEWhuargWDm5Km6UYhP35pql+6WTm5HA4IugRTu5Xyq/Vc5zNDnYk/D8wIB82uaLgPFTsyFnPuBm+N7qQHzeHfsLhFshviNbiSKPfTNyWfgi2QoEorVyrTEDUN7zxwEMQFyf2L7W5alEWHpcfW5i7a8ZhnKhKuXCwweEHkIyvizKeFvZKXqr6QasOB8tUduUTa6m4NxebaYfNNr68BhiO77tuZTiCFa8li8BfUd/c53tjzNFQxE9NkagSHVafJ+LvdJ0bBFx4vAXp2102NE+6z02MqrNv4X/E8g9wiMq91ji/Ex5bbRhPHjC9+BYLzvVnItROtxAn5KjhvKlxoyERdOnrJ06hdQTvS27dF7+xJ/PYksuPdlEezhT0/CT+N01KY0KVycXMNl5tZZrWdLMXN+MfhWht9LVKpTpsF8ZY0ScLzsANxVZCWt9/wF3ojcIjOQ3VkeaTRZJObkklpT2IGAaWznbmadtkFb46UlRcUDgXI4q3buM3aedDaGp5cSd72ijU/aWYyy5Ms2BRMBXfgD+9UzPKlS0UOsyMvlF0ZO/6d70Fegc0ndr5WO8c9aqD6D6rYE4d1X67DcvMuAeBjqjFkKCLbVb4RvsdRmLejL+Z7ywkV5mb0M8Xfyd47TNVh5KRt1XU9IawjGGZIE=
  - secure: fbeUa1dIqjxViOY9vVXHnijs0zuiI+H/XqcRuQ5/V6BQKisyv44ek2XQvJv9HqDJO3abhGpuwU50awHkdC70XBIdJ0IcECpCjPFDD9MX+qQu2thVU1d9stvPT6QgMc5GIYcPDCKp8QZjDTEH4hNQo8rmHwzqZQyWB2Mza4fvwrG8f+k9OwM2jE6fmwfWbzZLDG77GVZpJRz/zjbjzHub4Nn1pWrHxm7fhjQp0lW9SxgMpvAUCuqSQ1JayfRIEJJ13gnerV7I6UXEKpa9ToWZ71eOcoG9oO+Z9gGMB+9Aq17Q8aX3IJRE57rtwLa4f23zqp3y1A4AoO9hyTj4R7d+enFhX+FqXB0Wu49hEqxctMyP+ibH69DyEfZMLLLw0rhP6oiTEpj036lJ4mOxZGTLzHIVeXMAWqMcWtyktZtIg3HCU5cs2RG3IgbuqG6PpAkX9op2CimU68ostbjVT/T+KerytX3kHHc2V6JTIF5qi+uSs2hc/UNwlwVMVxFjVRlQL55gaLU4vvS1RJ8lJp/NTdJPCn5Q4rJR1S03IxoFqDHO+2ififj2MZPhDOxAnxfQqHr69xPQhSSQ3y8us/vQ0EzdTla5/FKMomQxLfMTstZr8OoSK992FRTiVFrj/AIllTtBwCslEjba+ddaLumLWHOUNZoib2/rPaBzdpSQq+4=
  - secure: V7B3L9L1piSb+6FbAjUr8fBkq6NZYKHjkcBM8I2ALMNsZIlWDu3Zp1Vw/+Cu597DS0E9BxVa5DEKqBrpr7+zjOkFzG3nAwvCqrc1blMRXn1MaJPv/mYe0i4q+1GaDAttzo3FnCG5uyLA3filyiv5TyCH+b5+FlhGasA9H/VGK9kfc5+sCFXO9dHc+pPKNH1ISWQD6LF6s+Ojofc1Du8tD1GEFlrqTTb3ij4wGvsI8EJayrWN9lKOZYbMp+5eLFcTR/O1BvFHqAO+S24JujoxlCx1se92fMmbZ2VLSfTB87+bIw0cp5NfdFIzGd1gY5f4/NHcYu1WC+jCsiGUB7bcwORI756+5H7NGaabVyo6tAm2XZGv59qLZ7qwtzY7G0tKBZ7dKDVkYmWCK7b3J76mHc5udOtFYWcF44OUQB37ijqXOLGImz4tmotEmF8Mru/RAZbNZMFF/gt6hr5b8tUgI5ErUmZEbtEQsO1346POh3CrPBSgkIaVlFQNzEq+QSVDtNoeqcSYTOCznq4bvX513Nb4KLm57qybsodgly3eaSsKoXgkCEMygxzkC/wQtTPd30IXrXkO2ZQo/q4ZTeuQGTaokFv1k9FPpY/tsRCwmHREup9ZlKVDvFmUT8Up/TBpFjuRMvZUDlfb5zT9B/Vd+D9KsBn/pG35xZOA71/mCxM=
before_install:
- sudo apt-get update
- sudo apt-get install --only-upgrade -y oracle-java8-installer
- mkdir -p ~/.gnupg
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out ~/.gnupg/secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out ~/.gnupg/pubring.gpg
  -d
- echo "<settings><servers><server><id>ossrh</id><username>\${OSSRH_JIRA_USERNAME}</username><password>\${OSSRH_JIRA_PASSWORD}</password></server></servers></settings>"
  > ~/.m2/settings.xml
install:
- wget ${ACTIVATOR_ZIP_URL}
- unzip -q ${ACTIVATOR_ZIP_FILE}
script:
- mvn clean install -Dgpg.passphrase="${GPG_PASSPHRASE}" --settings
  ~/.m2/settings.xml
after_success:
- .travis/deploy.sh
- .travis/build_dependents.sh
after_script:
- rm ~/.gnupg/secring.gpg
- rm ~/.gnupg/pubring.gpg
- rm ~/.m2/settings.xml
notifications:
  email: true
branches:
  only:
  - master
  - R17
scala:
- 2.11.8
cache:
  directories:
  - .autoconf
  - ~/.m2
  - ~/.sbt
  - ~/.ivy
